server:
  #端口号
  port: 92000

spring:
  application:
    #应用名称
    name: api-doc

logging:
  config: classpath:logback-dev.xml
  file:
    name: logs/api-doc

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://192.168.16.239:8848/nacos/
    routes:
      - name: 运营商企业WEB端 - 系统服务
        serviceName: company-web
        namespaceId: mos
        location: /v2/api-docs?group=企业WEB端 - 系统服务
        servicePath: /ice/companyweb
        order: 200