server:
  #端口号
  port: 90000

spring:
  application:
    #应用名称
    name: gateway

  cloud:
    #nacos  开发及测试可以用单节点模式，生产建议用集群模式
    nacos:
      #服务注册与发现
      discovery:
        server-addr: 192.168.16.239:8848
        namespace: mos

    sentinel:
      transport:
        dashboard: 192.168.16.239:53000
        port: 58719

    #网关配置
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company-web
          uri: lb://company-web
          predicates: Path=/ice/companyweb/**
          filters: StripPrefix= 2

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #mq
  rabbitmq:
    host: 192.168.16.239
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5

  main:
    allow-bean-definition-overriding: true

  zipkin:
    base-url: http://192.168.16.239:54000/
    discovery-client-enabled: false
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1

management:
  #端点检查
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-dev.xml
  file:
    name: logs/gateway