server:
  #端口号
  port: 91001

spring:
  application:
    #应用名称
    name: company-web

  #数据源
  datasource:
    #阿里druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池属性
    druid:
      username: prod
      password: MysqlDmpDev
      url: jdbc:mysql://192.168.16.239:3306/dmp_common?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 192.168.16.239
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        login-username: admin
        login-password: gt_admin
        enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    #nacos  开发及测试可以用单节点模式，生产建议用集群模式
    nacos:
      #服务注册与发现
      discovery:
        server-addr: 192.168.16.239:8848
        namespace: mos

    sentinel:
      transport:
        dashboard: 192.168.16.239:53000
        port: 58719

  #redis
  redis:
    host: 192.168.16.239
    port: 6390
    password: GateonDmpDev
    timeout: 5000
    database: 5

  #缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      #如果指定前缀就用指定前缀，如果没指定就用缓存名字
      #key-prefix: cache_
      #use-key-prefix: true
      cache-null-values: true

  #mq
  rabbitmq:
    host: 192.168.16.239
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5

  main:
    allow-bean-definition-overriding: true

  zipkin:
    base-url: http://192.168.16.239:54000/
    discovery-client-enabled: false
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1

management:
  #端点检查
  endpoints:
    web:
      exposure:
        include: "*"

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false

logging:
  config: classpath:logback-dev.xml
  file:
    name: logs/mg-company-web

xxl:
  job:
    admin:
      addresses: http://192.168.16.239:59999/xxl-job-admin
    accessToken:
    executor:
      appname: company-web
      address:
      ip:
      port: 93001
      logpath: /data/applogs/xxl-job/jobhandler/mg/${spring.application.name}
      logretentiondays: 30

rocketmq:
  name-server: 192.168.16.239:9876
  producer:
    group: ice-company
    send-message-timeout: 3000